flowchart TD

id4(Process feedback, 
changes in protocol and 
ticket text when needed,
and await approval
from ELAN research committee
and ELAN GP Steering committee)
id6(Await approval,
and process feedback
if applicable from
ELAN research committee
and ELAN GP Steering committee) 