flowchart TD
subgraph external [Can be performed whenever]
    idF1(Request data from Hadoks) --> idF2(Update your ticket)
end

id2 --> idF1

style idF1 fill:#728bad
style idF2 fill:#728bad
style external fill:#a2b2c9, stroke:#a57ca5
click idF1 "https://elan-dcc.github.io/researchers/hadoks" "hadoks" _blank
click idF2 "https://elanresearch.nl" "ELAN research" _blank