flowchart TD
subgraph external [Can be performed whenever]
    idB1(Request permission
    from Parnassia) --> idB2(Upload approval
    from Parnassia
    to ticket)
end

id2 --> idB1

style idB2 fill:#728bad
style external fill:#a2b2c9, stroke:#a57ca5
click idB2 "https://elanresearch.nl" "ELAN research" _blank
