flowchart TD
subgraph external [These actions can be performed whenever]
    idB1(Request permission
    from Parnassia) --> idB2(Upload approval
    from Parnassia
    to ticket)
end

id2 --> idB1

style idB2 fill:#c594c3
style external fill:#efd5ef, stroke:#a57ca5
click idB2 "https://elanresearch.nl" "ELAN research" _blank